name: Auto DailyNews

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0:10 运行，相当于北京时间 9:00
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python run.py
        env:
          HITOKOTO: ${{ secrets.HITOKOTO }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_ARCHIVE: ${{ secrets.BARK_ARCHIVE }}
          BARK_GROUP: ${{ secrets.BARK_GROUP }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          BARK_ICON: ${{ secrets.BARK_ICON }}
          BARK_LEVEL: ${{ secrets.BARK_LEVEL }}
          BARK_URL: ${{ secrets.BARK_URL }}
          CONSOLE: ${{ secrets.CONSOLE }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          FSKEY: ${{ secrets.FSKEY }}
          GOBOT_URL: ${{ secrets.GOBOT_URL }}
          GOBOT_QQ: ${{ secrets.GOBOT_QQ }}
          GOBOT_TOKEN: ${{ secrets.GOBOT_TOKEN }}
          GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
          GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
          GOTIFY_PRIORITY: ${{ secrets.GOTIFY_PRIORITY }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          DEER_KEY: ${{ secrets.DEER_KEY }}
          DEER_URL: ${{ secrets.DEER_URL }}
          CHAT_URL: ${{ secrets.CHAT_URL }}
          CHAT_TOKEN: ${{ secrets.CHAT_TOKEN }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          WE_PLUS_BOT_TOKEN: ${{ secrets.WE_PLUS_BOT_TOKEN }}
          WE_PLUS_BOT_RECEIVER: ${{ secrets.WE_PLUS_BOT_RECEIVER }}
          WE_PLUS_BOT_VERSION: ${{ secrets.WE_PLUS_BOT_VERSION }}
          QMSG_KEY: ${{ secrets.QMSG_KEY }}
          QMSG_TYPE: ${{ secrets.QMSG_TYPE }}
          QYWX_ORIGIN: ${{ secrets.QYWX_ORIGIN }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_API_HOST: ${{ secrets.TG_API_HOST }}
          TG_PROXY_AUTH: ${{ secrets.TG_PROXY_AUTH }}
          TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST }}
          TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT }}
          AIBOTK_KEY: ${{ secrets.AIBOTK_KEY }}
          AIBOTK_TYPE: ${{ secrets.AIBOTK_TYPE }}
          AIBOTK_NAME: ${{ secrets.AIBOTK_NAME }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_SSL: ${{ secrets.SMTP_SSL }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_NAME: ${{ secrets.SMTP_NAME }}
          PUSHME_KEY: ${{ secrets.PUSHME_KEY }}
          PUSHME_URL: ${{ secrets.PUSHME_URL }}
          CHRONOCAT_QQ: ${{ secrets.CHRONOCAT_QQ }}
          CHRONOCAT_TOKEN: ${{ secrets.CHRONOCAT_TOKEN }}
          CHRONOCAT_URL: ${{ secrets.CHRONOCAT_URL }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_BODY: ${{ secrets.WEBHOOK_BODY }}
          WEBHOOK_HEADERS: ${{ secrets.WEBHOOK_HEADERS }}
          WEBHOOK_METHOD: ${{ secrets.WEBHOOK_METHOD }}
          WEBHOOK_CONTENT_TYPE: ${{ secrets.WEBHOOK_CONTENT_TYPE }}
          # 在这里添加其他需要传递给 Python 脚本的 secret 环境变量
